/******************************************************************************
 *
 * Project    : Robonix AccelMeter
 * Module     : Model
 * File       : ModelObjects.h
 *
 * Version    : 1.0.0
 *
 * Description:
 *      Firmware Runtime Data Objects
 *
 ******************************************************************************/

#ifndef MODEL_OBJECTS_H
#define MODEL_OBJECTS_H

#include <Arduino.h>

#include "ModelConfig.h"
#include "ModelTypes.h"

/*=============================================================================
    Measurement Frame
=============================================================================*/

struct MeasurementFrame
{
    Vector3f raw;

    Vector3f calibrated;

    Vector3f filtered;

    float magnitude;

    Timestamp timestamp;

    uint32_t frameNumber;
};

/*=============================================================================
    Statistics
=============================================================================*/

struct StatisticsData
{
    float rms;

    float peak;

    float mean;

    float sampleRate;
};

/*=============================================================================
    Calibration
=============================================================================*/

struct CalibrationData
{
    /*
        Calibration Status
    */
    CalibrationState state;

    /*
        Factory Calibration Offset
        Permanent calibration generated by calibration procedure.
    */
    Vector3f factoryOffset;

    /*
        Measurement Zero Offset
        Captured every time a new measurement session starts.
    */
    Vector3f zeroOffset;
};

/*=============================================================================
    Device Configuration
=============================================================================*/

struct DeviceConfiguration
{
    uint16_t sampleRate;

    AccelerationUnit unit;

    FilterType filterType;
};

/*=============================================================================
    Device Status
=============================================================================*/

struct DeviceStatus
{
    FirmwareState firmware;

    SensorState sensor;

    CommunicationState serial;

    CalibrationState calibration;
};

#endif // MODEL_OBJECTS_H