/******************************************************************************
 *
 * Project    : Robonix AccelMeter
 * Module     : Model
 * File       : ModelObjects.h
 *
 * Version    : 3.0.0
 *
 * Description:
 *      Firmware Runtime Data Objects.
 *
 ******************************************************************************/
#ifndef MODEL_OBJECTS_H
#define MODEL_OBJECTS_H

#include <Arduino.h>

#include "ModelConfig.h"
#include "ModelTypes.h"
//#include "DisplayTypes.h"
/*=============================================================================
    Measurement Frame
=============================================================================*/

struct MeasurementFrame
{
    Vector3f raw;

    Vector3f calibrated;

    Vector3f filtered;

    float magnitude;

    Timestamp timestamp;

    uint32_t frameNumber;
};

/*=============================================================================
    Statistics
=============================================================================*/

struct StatisticsData
{
    float rms;

    float peak;

    float mean;

    float sampleRate;
};

/*=============================================================================
    Calibration
=============================================================================*/

struct CalibrationData
{
    /*
        Calibration Status
    */

    CalibrationState state;

    /*
        Factory Offset
        Permanent offset generated by calibration procedure.
    */

    Vector3f factoryOffset;

    /*
        Zero Offset
        Captured at the beginning of every measurement session.
    */

    Vector3f zeroOffset;
};

/*=============================================================================
    Display
=============================================================================*/

struct DisplayData
{
    /*
        Current page
    */

    DisplayPage page;

    /*
        Refresh mode
    */

    DisplayRefresh refresh;

    /*
        Page changed request
    */

    bool pageChanged;

    /*
        Display enable
    */

    bool enabled;
};

/*=============================================================================
    Device Configuration
=============================================================================*/

struct DeviceConfiguration
{
    uint16_t sampleRate;

    AccelerationUnit unit;

    FilterType filterType;
};

/*=============================================================================
    Device Status
=============================================================================*/

struct DeviceStatus
{
    FirmwareState firmware;

    SensorState sensor;

    CommunicationState serial;

    CalibrationState calibration;
};

#endif // MODEL_OBJECTS_H